FROM ghcr.io/theshellland/rust:latest

ENV RUST_BACKTRACE=1
ENV RUST_BACKTRACE=full
ENV COLORBT_SHOW_HIDDEN=1
ENV DEBUG=false
ENV TRACE=""

ENV VEILID_CONFIG=/root/.config/veilid/veilid-server.conf

# install python
RUN apt update && \
    apt install -y python3 && \
    apt clean && \
    rm -rf /var/lib/apt/lists/\* /tmp/\* /var/tmp/*

RUN git clone https://github.com/TheShellLand/antsable && \
    cd antsable && \
    bash install-ansible.sh && \
    bash ansible-local.sh playbooks/apt-upgrade.yml -v && \
    bash ansible-local.sh playbooks/build-tools.yml -v && \
    bash ansible-local.sh playbooks/python3.yml -v && \
    bash ansible-local.sh playbooks/apt-clean.yml -v


# install veilie
COPY install.sh .
RUN bash install.sh

COPY entry.sh /entry.sh

# config
VOLUME /root/.config/veilid/

# State holds the node ID etc. to persist between runs
VOLUME /root/.local/share/veilid/

# logs
VOLUME /logs

# data
VOLUME /var/db/veilid-server

# listen_address
# IPC is used by default
EXPOSE 5959

# I see this port used in logs
EXPOSE 5150

# grpc_endpoint
EXPOSE 4317

EXPOSE 80
EXPOSE 443

ENTRYPOINT ["/bin/bash", "/entry.sh"]
