daemon:
    enabled: false
client_api:
    ipc_enabled: false
    enabled: true
    network_enabled: true
    listen_address: '127.0.0.1:5959'
logging:
    system:
        enabled: false
        level: info
    terminal:
        enabled: true
        level: info
    api:
        enabled: true
        level: info